apiVersion: v1
kind: Secret
metadata:
  name: paymentsecret
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: app
    microname: payment
type: Opaque
data:
  AMQP_USER: "cm9ib3Nob3A="
  AMQP_PASS: "cm9ib3Nob3AxMjM="