apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: database
    microname: mongodb
spec:
  selector:
    project: roboshop
    purpose: rsdemo
    tier: database
    microname: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None