apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: app
    microname: user
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/users"
  REDIS_HOST: "redis://redis:6379"