apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: app
    microname: user
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      purpose: rsdemo
      tier: app
      microname: user
  template:
    metadata:
      labels:
        project: roboshop
        purpose: rsdemo
        tier: app
        microname: user
    spec:
      containers:
        - name: user
          image: satyology/useroptimized
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: user