apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: database
    microname: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="