apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: database
    microname: redis
spec:
  selector:
    project: roboshop
    purpose: rsdemo
    tier: database
    microname: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379