apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: app
    microname: shipping
spec:
  selector:
    project: roboshop
    purpose: rsdemo
    tier: app
    microname: shipping
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP