apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    purpose: rsdemo
    tier: app
    microname: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      purpose: rsdemo
      tier: app
      microname: cart
  template:
    metadata:
      labels:
        project: roboshop
        purpose: rsdemo
        tier: app
        microname: cart
    spec:
      containers:
        - name: cart
          image: {{ .Values.deployment.imageURL }}
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: cart